services:
  web:
    image: php:8.3-apache
    container_name: apache2-php
    ports:
      - "80:80"
    volumes:
      - ./docker/apache2/my-httpd.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./phpcode:/var/www/html/
    environment:
      - TZ=Europe/Budapest
    restart: unless-stopped
    networks:
      - backend
  
  mysql:
    image: mariadb:10.6-focal
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: learnmvc
      MYSQL_USER: user1
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend
      - mysql-phpmyadmin
    secrets:
      - mysql_root_password
      - mysql_password
    restart: unless-stopped
  
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./phpcode:/app
    working_dir: /app
    command: composer install
    networks: 
      - backend
   
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    networks:
      - mysql-phpmyadmin
    secrets:
      - mysql_root_password
      - mysql_password


networks:
  backend:
  frontend:
  mysql-phpmyadmin:
  
secrets:
  mysql_root_password:
    file: ./docker/secrets/mysql_root_password.txt
  mysql_password:
    file: ./docker/secrets/mysql_password.txt